[versions]
# Library versions
springDocVersion = "2.8.9"

mockitoVersion = "5.18.0"

logbackVersion = "1.5.18"

auth0Version = "3.0.7"

apacheCommonsVersion = "3.18.0"

# Plugin versions
springBootVersion = "3.5.4"

springDependencyManagementVersion = "1.1.7"

asciiDoctorVersion = "4.0.4"

[libraries]
springDoc = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springDocVersion" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockitoVersion" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logbackVersion" }
auth0 = { group = "com.okta.spring", name = "okta-spring-boot-starter", version.ref = "auth0Version" }
apache-commons-lang = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apacheCommonsVersion" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBootVersion" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion" }
asciiDoctor = { id = "org.asciidoctor.jvm.convert", version.ref = "asciiDoctorVersion" }
